deployment:
  tasks:
    - export REPOPATH=/home/jelsaby/repositories/jelsa/*
    - export SITEPATH=/home/jelsaby/repositories/jelsa/dist/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH